#!/usr/bin/env bash

set -e

cd "$(dirname "$0")/.."

echo "==> Detecting breaking changes"

TEST_PATHS=(
	tests/api-resources/top-level.test.ts
	tests/api-resources/characters.test.ts
	tests/api-resources/teams/teams.test.ts
	tests/api-resources/teams/logo.test.ts
	tests/api-resources/matches/matches.test.ts
	tests/api-resources/matches/commentary.test.ts
	tests/api-resources/episodes.test.ts
	tests/api-resources/quotes.test.ts
	tests/api-resources/believe.test.ts
	tests/api-resources/conflicts.test.ts
	tests/api-resources/reframe.test.ts
	tests/api-resources/press.test.ts
	tests/api-resources/coaching/coaching.test.ts
	tests/api-resources/coaching/principles.test.ts
	tests/api-resources/biscuits.test.ts
	tests/api-resources/pep-talk.test.ts
	tests/api-resources/stream.test.ts
	tests/api-resources/team-members.test.ts
	tests/api-resources/webhooks.test.ts
	tests/api-resources/health.test.ts
	tests/api-resources/version.test.ts
	tests/api-resources/client/client.test.ts
	tests/api-resources/client/ws.test.ts
	tests/api-resources/client/ticket-sales.test.ts
	tests/index.test.ts
)

for PATHSPEC in "${TEST_PATHS[@]}"; do
    # Try to check out previous versions of the test files
    # with the current SDK.
    git checkout "$1" -- "${PATHSPEC}" 2>/dev/null || true
done

# Instead of running the tests, use the linter to check if an
# older test is no longer compatible with the latest SDK.
./scripts/lint
